{{- if .Values.loadBalancer.enabled }}
  {{- $fullName := include "cp-kafka.fullname" . }}
  {{- $brokers := .Values.brokers | int }}
  {{- $servicePort := .Values.loadBalancer.servicePort }}
  {{- $internal := .Values.loadBalancer.internal }}
  {{- $subnet := .Values.loadBalancer.subnet }}
  {{- $root := . }}
  {{- range $i, $e := until $brokers }}
    {{- $externalListenerPort := add $root.Values.loadBalancer.firstListenerPort $i }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" $root }}-{{ $i }}-lb
  labels:
    app: {{ include "cp-kafka.name" $root }}
    chart: {{ template "cp-kafka.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: {{ $internal | quote }}
    {{- if $subnet }} service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ $subnet | quote }} {{- end}}
spec:
  type: LoadBalancer
  ports:
    - name: external-broker
      port: {{ $servicePort }}
      targetPort: {{ $externalListenerPort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
  selector:
    app: {{ include "cp-kafka.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}
